{% set version = "isis6" %} # synched up to isis dependencies for this version

package:
  name: libpointmatcher
  version: {{ version }}

source:
  git_url: https://github.com/oleg-alexandrov/libpointmatcher.git
  git_tag: 0f909cf

# The custom patches have been applied to the code and checked in to
# the repo, so they need not be applied here.
#  patches:
# Custom tweaks for ASP
#    - 0001_custom_lib_changes.patch
# Build fixes
#    - 0002_CMake_fix.patch
# Mac link issue fix
#    - 0003_turn_off_utest.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - libgcc-ng >=9.3.0    # [linux]
    - libstdcxx-ng >=9.3.0 # [linux] 
    - llvm-openmp >=12.0.1 # [osx] 
    - boost 1.68.0.*
    - eigen 3.4.0
    - libnabo isis6

  run:
    - libgcc-ng >=9.3.0    # [linux]
    - libstdcxx-ng >=9.3.0 # [linux] 
    - llvm-openmp >=12.0.1 # [osx] 
    - boost 1.68.0.*
    - eigen 3.4.0
    - libnabo isis6

test:
  commands:
  files:

about:
  home: https://github.com/ethz-asl/libpointmatcher
  license: BSD
  summary: An "Iterative Closest Point" library for 2-D/3-D mapping in Robotics
  description:

extra:
  recipe-maintainers:
