{% set version = "isis5.0.1" %} # synched up to isis dependencies for this version

package:
  name: libpointmatcher
  version: {{ version }}

source:
  git_url: https://github.com/oleg-alexandrov/libpointmatcher.git
  git_tag: f09bdfe
  patches:
# Custom tweaks for ASP
    - 0001_custom_lib_changes.patch
# Build fixes
    - 0002_CMake_fix.patch
# Mac link issue fix
    - 0003_turn_off_utest.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost   1.68.0
    - eigen   3.3.7
    - libnabo isis5.0.1
  run:
    - boost   1.68.0
    - eigen   3.3.7
    - libnabo isis5.0.1

test:
  commands:
  files:

about:
  home: https://github.com/ethz-asl/libpointmatcher
  license: BSD
  summary: An "Iterative Closest Point" library for 2-D/3-D mapping in Robotics
  description:

extra:
  recipe-maintainers:
