{% set version = "isis5.0.1_bugfix2" %} # synched up to isis dependencies for this version

package:
  name: libpointmatcher
  version: {{ version }}

source:
  git_url: https://github.com/oleg-alexandrov/libpointmatcher.git
  git_tag: 08515d5

# The custom patches have been applied to the code and checked in to
# the repo, so they need not be applied here.
#  patches:
# Custom tweaks for ASP
#    - 0001_custom_lib_changes.patch
# Build fixes
#    - 0002_CMake_fix.patch
# Mac link issue fix
#    - 0003_turn_off_utest.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - llvm-openmp               12.0.1         # [osx]
    - _libgcc_mutex             0.1            # [linux]
    - gcc_impl_linux-64         7.5.0          # [linux]
    - gcc_linux-64              7.5.0          # [linux]
    - libgcc                    7.2.0          # [linux]
    - libgcc-devel_linux-64     7.5.0          # [linux]
#    - libgcc-ng                 11.1.0         # [linux]
    - boost                     1.68.0
    - eigen                     3.3.7
    - libnabo                   isis5.0.1
    - krb5                      1.16.3
    - libssh2                   1.8.0 
    - freetype                  2.7        
    - ncurses                   6.2            
    - openssl                   1.0.2u         
    - python                    3.6.7          
    - python-dateutil           2.8.2          
    - python_abi                3.6            
    - jpeg                      9d
    - openjpeg                  2.1.0
    - libpng                    1.6.37
    - libtiff                   4.0.10
    - zlib                      1.2.11
    - openblas                  0.2.19
    - libxml2                   2.9.9
    - libblas                   3.8.0
    - libiconv                  1.15
    - numpy                     1.13
    - isis                      5.0.1
    - libopenblas               0.3.10 

  run:
    - llvm-openmp               12.0.1         # [osx]
    - _libgcc_mutex             0.1            # [linux]
    - gcc_impl_linux-64         7.5.0          # [linux]
    - gcc_linux-64              7.5.0          # [linux]
    - libgcc                    7.2.0          # [linux]
    - libgcc-devel_linux-64     7.5.0          # [linux]
#    - libgcc-ng                 11.1.0         # [linux]
    - boost                     1.68.0
    - eigen                     3.3.7
    - libnabo                   isis5.0.1
    - krb5                      1.16.3         
    - libssh2                   1.8.0         
    - freetype                  2.7        
    - ncurses                   6.2            
    - openssl                   1.0.2u         
    - python                    3.6.7          
    - python-dateutil           2.8.2          
    - python_abi                3.6            
    - jpeg                      9d
    - openjpeg                  2.1.0
    - libpng                    1.6.37
    - libtiff                   4.0.10
    - zlib                      1.2.11
    - openblas                  0.2.19
    - libxml2                   2.9.9
    - libblas                   3.8.0
    - libiconv                  1.15
    - numpy                     1.13
    - isis                      5.0.1
    - libopenblas               0.3.10 

test:
  commands:
  files:

about:
  home: https://github.com/ethz-asl/libpointmatcher
  license: BSD
  summary: An "Iterative Closest Point" library for 2-D/3-D mapping in Robotics
  description:

extra:
  recipe-maintainers:
