{% set version = "asp3.5.0" %} # synched up to isis dependencies for this version

package:
  name: libpointmatcher
  version: {{ version }}

source:
  git_url: https://github.com/NeoGeographyToolkit/libpointmatcher
#  git_tag: 0f909cf

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake 3.27.9

  host:
    - boost 1.78.0
    - eigen 3.4.0
    - libnabo
    - llvm-openmp 16.0.6

  run:
    - boost 1.78.0
    - eigen 3.4.0
    - libnabo
    - llvm-openmp 16.0.6

test:
  commands:
  files:

about:
  home: https://github.com/ethz-asl/libpointmatcher
  license: BSD
  summary: An "Iterative Closest Point" library for 2-D/3-D mapping in Robotics
  description:

extra:
  recipe-maintainers:
